### ISSUE TITLE
Smaller bins on y-axis histogram of explorers

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsqc#112]
When looking at mutations in large datasets the time historgram is usually overwhelmed by the recent past. Narrower bins might help to get some resolution when we have horizontal banding

**Comment by jeromekelleher** [comment]
The "auto" bins are much better I think, nice.

What if we a check-box for optionally log-scaling time? So, if ticked, we use ``log(1 + df.time)`` in each of the plots?

As a quick check, could you try manually do this and show what it looks like (without the checkbox)?

**Comment by savitakartik** [comment]
Here's a plot for the same data with log time on the y axis.

https://github.com/tskit-dev/tsqc/assets/25925005/cd857937-f1ff-4f2f-8de1-6df1ffd1e117

**Comment by jeromekelleher** [comment]
Looks good - log time is definitely a handy option to have.  Let's add it as a check-box option?

**Comment by savitakartik** [comment]
> Looks good - log time is definitely a handy option to have.  Let's add it as a check-box option?

Sure, we've got a log y checkbox already for two other plots on the tab. I'll try and reuse that.
