### ISSUE TITLE
show tree boundaries in mutations plot

### ISSUE THREAD

**Issue by savitakartik** [tskit-dev/tsqc#122]
In the mutations panel, it might be a helpful addition to overlay tree sequence breakpoints as vertical lines on the plot.
In the initial view we might want to datashade this info.

**Comment by jeromekelleher** [comment]
I wonder if we could do a datashade of this, and then overlay it on top of the standard mutation view?

https://holoviews.org/reference/containers/plotly/Overlay.html#overlay
