### ISSUE TITLE
Performance degradation in Mutations tab due to recent changes

### ISSUE THREAD

**Issue by duncanMR** [tskit-dev/tsqc#154]
I'm finding it very difficult to use tsqc in the Genomics England virtual desktop environment since all the recent changes to the Mutations tab in particular. The environment has extremely poor performance, particularly for graphics. It takes over a minute to render the first view of the Mutations (freezing the browser), and it freezes for 20-60 seconds when zooming in and out which makes it hard to use. 

If I revert to the [February 27 version](https://github.com/tskit-dev/tsqc/commit/9c2fe75077d938557de7706ee1a95683bd2c54f7), just before the [Mutation page overhaul which added tree breakpoints](https://github.com/tskit-dev/tsqc/commit/1c61ce4d6e370eeda09e6464f71c323a1bf822c0), the performance greatly improves to the point that I can zoom in and out of the mutations with only a second or two of lag. The performance takes a big hit when I move to the Mutation page overhaul commit, so I think the problem lies with the tree breakpoints pane. It looks to me like the tree breakpoints might not be Datashaded: there are 615 000 trees in this tree sequence, so that could be problematic:

![image](https://github.com/tskit-dev/tsqc/assets/5416474/1d6a67ae-7d63-4fed-a83f-18c48f967690)

However, the current version works fine on my laptop, even for large tree sequences. I think it might work well to show a density plot of the breakpoints when zoomed out, then only render the breakpoint lines when we have sufficiently few mutations in view that we can overlay the mutation data with hover info?

**Comment by jeromekelleher** [comment]
The tree breakpoints may well be the problem. Can you try with this widget commented out?

**Comment by savitakartik** [comment]
I had simillar thoughts about replacing the histogram with the breakpoint lines when zoomed in enough. I'll look into that later but for now I'll just remove that widget since the histogram is conveying pretty much the same information. Have sample nodes been assigned populations in the Genomics England trees? I wonder if population frequencies are being calculated, that could also explain the initial delay. For this I plan to implement a switch to turn this off by default.

**Comment by duncanMR** [comment]
> The tree breakpoints may well be the problem. Can you try with this widget commented out?

That fixes the problem, including the long delay when loading the mutations tab: it's still a bit less snappy than the February version, but it is manageable.

> I had simillar thoughts about replacing the histogram with the breakpoint lines when zoomed in enough. I'll look into that later but for now I'll just remove that widget since the histogram is conveying pretty much the same information. Have sample nodes been assigned populations in the Genomics England trees? I wonder if population frequencies are being calculated, that could also explain the initial delay. For this I plan to implement a switch to turn this off by default.

Sounds good! We haven't assigned populations to samples in the Genomics England trees yet, but I could do that quite easily if you'd like me to test it in future.
