### ISSUE TITLE
Popgen stats 

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsqc#43]
It would be useful to be able to display popgen stats like diversity along the genome, both site and branch (maybe the ratio) with options to specify window size, and other parameters.

**Comment by jeromekelleher** [comment]
This will be on it's own page, not necessarily following the conventions about using dataframes etc.

**Comment by jeromekelleher** [comment]
Should fit neatly with Holoview curve

**Comment by savitakartik** [comment]
implemented with PR #72 .
