### ISSUE TITLE
allele frequency spectrum 

### ISSUE THREAD

**Issue by savitakartik** [tskit-dev/tsqc#75]
The allele frequency spectrum might be a useful addition to the popgen page (addressed in PR #72 and issue #43).

**Comment by hyanwong** [comment]
I think we should also plot the AFS from branch lengths (as long as time_units is not `uncalibrated`) and the AFS from counting individual sites. See https://github.com/tskit-dev/tsdate/issues/370#issuecomment-1948785825

**Comment by jeromekelleher** [comment]
Would dividing one by the other be a useful diagnostic?

**Comment by hyanwong** [comment]
> Would dividing one by the other be a useful diagnostic?

Hmm, interesting. I'm not sure TBH. We think in the tsinfer trees, difference between site and branch versions of diversity probably reflect polytomies. We're not entirely sure about segregating sites (which is a "lumped together" version of the AFS.

Probably easiest to plot both as "standard" AFS plots for the time being.

**Comment by jeromekelleher** [comment]
Looks like we can just plot the raw values as a first pass anyway, that's useful in itself

**Comment by savitakartik** [comment]
Closing this issue as we now have a Frequency Spectra tab (PR #127). Will create a separate issue for planned changes to this tab.
