### ISSUE TITLE
Restructure as distributable Python package

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsqc#91]
We want to be able to install and run tsqc in the standard ways, like e.g.

```
python -m pip install tsqc
python -m tsqc path/to/trees/file
```

To do this, we need to restructure the code as a package.

- Add a directory ``tsqc``, and move all the Python files into it, so we have something like

```
    tsqc/
        __init__.py
        __main__.py  -> note, renamed from main.py
        model.py
        plot_helpers.py
        config.py
        pages/
            ... as before
```

- Add basic setup.py, pyproject.toml and setup.cfg (can follow example of tstrait here).
  We don't need to do to too much with these, proper packaging can be done as a follow-up.

There'll be two main changes involved here:

1) We'll have to change imports in the various files, but this can be done as minimally
as a first pass, e.g. changing ``import model`` to ``from . import model``

2) Running the server will be done via ``python -m tsqc`` instead of ``python main.py``.

How does this sound @savitakartik ?

**Comment by savitakartik** [comment]
Sounds great, @jeromekelleher and would definitely feel more packaged. Plan looks quite clear to me, only thing I didn't get right away was your comment on renaming main.py. I'll have a look at tstrait for some of these files.

**Comment by jeromekelleher** [comment]
Ha, well there's a good reason my comment about main.py didn't make sense! I forgot that ``__init__.py`` gets interpreted as markdown.

So, basically we're renaming the current ``main.py`` to ``tscq/__main__.py`` - that's the standard python "hook" to make a package executable like ``python -m <packagename>``.
